I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/script.rpy", line 2308, in script
    scene kuis salah
Exception: Image 'kuis' does not accept attributes 'salah'.

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/script.rpy", line 2308, in script
    scene kuis salah
  File "I:\RenPy\renpy-8.0.3-sdk\renpy\ast.py", line 1562, in execute
    show_imspec(self.imspec, atl=getattr(self, "atl", None))
  File "I:\RenPy\renpy-8.0.3-sdk\renpy\ast.py", line 1391, in show_imspec
    renpy.config.show(name,
  File "I:\RenPy\renpy-8.0.3-sdk\renpy\exports.py", line 733, in show
    if not base.find_target() and renpy.config.missing_show:
  File "I:\RenPy\renpy-8.0.3-sdk\renpy\display\image.py", line 421, in find_target
    self.target = target._duplicate(a)
  File "I:\RenPy\renpy-8.0.3-sdk\renpy\display\core.py", line 420, in _duplicate
    args.extraneous()
  File "I:\RenPy\renpy-8.0.3-sdk\renpy\display\core.py", line 283, in extraneous
    raise Exception("Image '{}' does not accept attributes '{}'.".format(
Exception: Image 'kuis' does not accept attributes 'salah'.

Windows-10-10.0.19045 AMD64
Ren'Py 8.1.0.23051307
 
Sat Jun 10 23:12:56 2023
